networks:
  fraud-detection:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - fraud-detection

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - fraud-detection
    depends_on:
      - zookeeper

  influxdb:
    image: influxdb:2.0
    ports:
      - "8086:8086"
    networks:
      - fraud-detection

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - fraud-detection
  #c'est l'APPLICATION JAVA qui va se connecter avec kafka
  fraud-detection:
    image: detectionapp:latest
    networks:
      - fraud-detection
